name: Cache-Clean

on:
  schedule:
    - cron: 0 20 * * 0
  workflow_dispatch:

permissions: write-all

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  auto_clean:
    runs-on: ubuntu-22.04
    steps:
      - name: 检出代码
        uses: actions/checkout@main

      - name: 清理缓存
        run: gh cache delete --all
